on: workflow_dispatch

name: Valheim Server Management

jobs:
  stop:
    name: Stop Valheim Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: aws ec2 stop-instances
      run: |
        aws ec2 stop-instances --instance-ids ${{ secrets.INSTANCE_ID }}
